seed: 42
n_policies: 2000
n_months: 12  # persist only first 12; generate 15 internally
n_months_internal: 15  # for 3-month lookahead
drift_start_month: "2023-07"
train_months: ["2023-01", "2023-08"]
val_months: ["2023-09", "2023-10"]
test_months: ["2023-11", "2023-12"]
n_tuning_trials: 20
shap_max_samples: 500
rag_top_k: 3

